server:
  run_mode: "debug"
  addr: ":3333"
  read_timeout: 2 #minute
  write_timeout: 2 #minute

pgsql:
  host: "db_postgres"
  port: 5432
  dbname: "recruitment_dev"
  user: "postgres"
  password: ""
  max_idle_conns: 100
  max_open_conns: 100
  max_life_seconds: 86400

sso:
  addr: "https://dev.back.sso.hustunique.com/api/v1"

redis:
  dsn: "redis://default:{password}@db_redis:6379/{database}"

sms:
  token:
  register_code_template_id:
  reset_password_code_template_id:

cos:
  cos_url:
  cos_secret_id:
  cos_secret_key:
